# Generated by Django 4.0.5 on 2022-06-11 18:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2),
        ),
    ]
